### ISSUE TITLE
Trying to open closed database object

### ISSUE THREAD

**Issue by dawidsamolyk** [dawidsamolyk/Android-Crawler#44]
Crawl page. Open that page in History tab.

07-11 11:47:52.493: E/AndroidRuntime(1826): FATAL EXCEPTION: main
07-11 11:47:52.493: E/AndroidRuntime(1826): Process: edu.uz.crawler, PID: 1826
07-11 11:47:52.493: E/AndroidRuntime(1826): java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteQuery: SELECT _id, DATE, WEBURL, TITLE, FOUND_TOPICS, CONTENT FROM Pages
07-11 11:47:52.493: E/AndroidRuntime(1826):     at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
07-11 11:47:52.493: E/AndroidRuntime(1826):     at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:58)
07-11 11:47:52.493: E/AndroidRuntime(1826):     at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:152)
07-11 11:47:52.493: E/AndroidRuntime(1826):     at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:124)
07-11 11:47:52.493: E/AndroidRuntime(1826):     at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:214)
07-11 11:47:52.493: E/AndroidRuntime(1826):     at android.widget.CursorAdapter.getItemId(CursorAdapter.java:223)
07-11 11:47:52.493: E/AndroidRuntime(1826):     at android.widget.AbsListView.onSaveInstanceState(AbsListView.java:1826)
07-11 11:47:52.493: E/AndroidRuntime(1826):     at android.view.View.dispatchSaveInstanceState(View.java:13669)
07-11 11:47:52.493: E/AndroidRuntime(1826):     at android.view.ViewGroup.dispatchFreezeSelfOnly(ViewGroup.java:2879)
07-11 11:47:52.493: E/AndroidRuntime(1826):     at android.widget.AdapterView.dispatchSaveInstanceState(AdapterView.java:792)
07-11 11:47:52.493: E/AndroidRuntime(1826):     at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:2865)
07-11 11:47:52.493: E/AndroidRuntime(1826):     at android.view.View.saveHierarchyState(View.java:13652)
07-11 11:47:52.493: E/AndroidRuntime(1826):     at android.support.v4.app.FragmentManagerImpl.saveFragmentViewState(FragmentManager.java:1614)
07-11 11:47:52.493: E/AndroidRuntime(1826):     at android.support.v4.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:1634)
07-11 11:47:52.493: E/AndroidRuntime(1826):     at android.support.v4.app.FragmentManagerImpl.saveAllState(FragmentManager.java:1695)
07-11 11:47:52.493: E/AndroidRuntime(1826):     at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:547)
07-11 11:47:52.493: E/AndroidRuntime(1826):     at android.app.Activity.performSaveInstanceState(Activity.java:1298)
07-11 11:47:52.493: E/AndroidRuntime(1826):     at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1288)
07-11 11:47:52.493: E/AndroidRuntime(1826):     at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:3961)
07-11 11:47:52.493: E/AndroidRuntime(1826):     at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3372)
07-11 11:47:52.493: E/AndroidRuntime(1826):     at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3428)
07-11 11:47:52.493: E/AndroidRuntime(1826):     at android.app.ActivityThread.access$1100(ActivityThread.java:151)
07-11 11:47:52.493: E/AndroidRuntime(1826):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1332)
07-11 11:47:52.493: E/AndroidRuntime(1826):     at android.os.Handler.dispatchMessage(Handler.java:102)
07-11 11:47:52.493: E/AndroidRuntime(1826):     at android.os.Looper.loop(Looper.java:135)
07-11 11:47:52.493: E/AndroidRuntime(1826):     at android.app.ActivityThread.main(ActivityThread.java:5257)
07-11 11:47:52.493: E/AndroidRuntime(1826):     at java.lang.reflect.Method.invoke(Native Method)
07-11 11:47:52.493: E/AndroidRuntime(1826):     at java.lang.reflect.Method.invoke(Method.java:372)
07-11 11:47:52.493: E/AndroidRuntime(1826):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
07-11 11:47:52.493: E/AndroidRuntime(1826):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
07-11 11:47:52.508: E/eglCodecCommon(1826): glUtilsParamSize: unknow param 0x00000b44
07-11 11:47:52.554: E/eglCodecCommon(1826): glUtilsParamSize: unknow param 0x00000bd0
07-11 11:47:52.714: E/eglCodecCommon(1826): ***\* ERROR unknown type 0x0 (glSizeof,72)

**Comment by dawidsamolyk** [comment]
Resolved in "master".
